// Auto-generated command registry - DO NOT EDIT MANUALLY
// Generated by scripts/generate-command-registry.ts
// Run: bun run scripts/generate-command-registry.ts

import { join } from "path"
import { readdirSync, statSync, writeFileSync } from "fs"

const CMD_DIR = join(__dirname, "..", "src", "cli", "cmd")

// Commands that share loaders (aliases)
// Key = alias command name, Value = target command export name (from COMMAND_EXPORTS)
const ALIAS_MAP: Record<string, string> = {
  "auth": "providers",
  "plug": "PluginCommand", // plug.ts exports PluginCommand
}

// Commands to exclude from --help listing (but still available)
const HIDDEN_COMMANDS = new Set(["tui", "db"])

// Known command name mapping (filename -> export name)
const COMMAND_EXPORTS: Record<string, string> = {
  "cli": "CliCommand",
  "acp": "AcpCommand",
  "mcp": "McpCommand",
  "attach": "AttachCommand",
  "run": "RunCommand",
  "generate": "GenerateCommand",
  "debug": "DebugCommand",
  "account": "ConsoleCommand",
  "providers": "ProvidersCommand",
  "agent": "AgentCommand",
  "upgrade": "UpgradeCommand",
  "uninstall": "UninstallCommand",
  "serve": "ServeCommand",
  "web": "WebCommand",
  "models": "ModelsCommand",
  "stats": "StatsCommand",
  "export": "ExportCommand",
  "import": "ImportCommand",
  "github": "GithubCommand",
  "pr": "PrCommand",
  "session": "SessionCommand",
  "tui": "TuiThreadCommand",
  "plug": "PluginCommand",
  "memory": "MemoryCommand",
  "learning": "LearningCommand",
  "db": "DbCommand",
  "workflow": "WorkflowCommand",
  "send": "SendCommand",
  "gateway": "GatewayCommand",
  "pair": "PairCommand",
}

function generateRegistry(): string {
  const files = readdirSync(CMD_DIR)
    .filter(f => f.endsWith(".ts") && !f.endsWith(".test.ts") && !f.endsWith(".shared.ts"))
    .map(f => f.replace(/\.ts$/, ""))

  const commands: string[] = []
  const loaderLines: string[] = []
  const loaderNames = new Set<string>()

  for (const name of files) {
    if (!COMMAND_EXPORTS[name]) continue

    const exportName = COMMAND_EXPORTS[name]
    const loaderName = `${exportName}Loader`
    const modulePath = `@gyccode/cli/cmd/${name}`

    if (!loaderNames.has(loaderName)) {
      loaderNames.add(loaderName)
      loaderLines.push(
        `const ${loaderName}: CommandLoader = { load: () => import("${modulePath}"), name: "${exportName}" }`
      )
    }

    commands.push(`  ${name}: ${loaderName},`)
  }

  const aliasEntries = Object.entries(ALIAS_MAP)
    .map(([alias, target]) => {
      const targetExport = COMMAND_EXPORTS[target]
      if (!targetExport) return ""
      const targetLoader = `${targetExport}Loader`
      return `  ${alias}: ${targetLoader},`
    })
    .filter(Boolean)
    .join("\n")

  return `// Auto-generated command registry - DO NOT EDIT MANUALLY
// Generated by scripts/generate-command-registry.ts

import type { Argv } from "yargs"
import { Effect } from "effect"

type CommandLoader = { load: () => Promise<Record<string, unknown>>; name: string }

${loaderLines.join("\n")}

export const COMMANDS: Record<string, CommandLoader> = {
${commands.join("\n")}
${aliasEntries ? "\n" + aliasEntries : ""}
}

// Canonical command keys (excluding aliases) used to render the full --help list.
// Derived from COMMANDS by keeping the first key for each unique loader — aliases
// (e.g. \`auth\`→providers, \`plug\`→plugin) share a loader reference and are skipped.
// Single source of truth: the list cannot drift when commands or aliases change.
export const COMMAND_KEYS = (() => {
  const seen = new Set<CommandLoader>()
  const keys: string[] = []
  for (const [key, loader] of Object.entries(COMMANDS)) {
    if (seen.has(loader)) continue
    seen.add(loader)
    if (${JSON.stringify(Array.from(HIDDEN_COMMANDS))}.includes(key)) continue
    if (key === "tui") continue
    keys.push(key)
  }
  return keys
})()

export const HIDDEN_COMMANDS_SET = new Set(${JSON.stringify(Array.from(HIDDEN_COMMANDS))})

export async function registerTui(cli: Argv, defaultEntry: boolean) {
  const mod = await import("@gyccode/cli/cmd/tui")
  const command = mod.TuiThreadCommand as unknown as Record<string, unknown>
  if (defaultEntry) cli.command({ ...command, command: "\$0 [project]" } as never)
  else cli.command({ ...command, describe: false } as never)
}

export async function registerCommand(cli: Argv, loader: CommandLoader) {
  const mod = await loader.load()
  cli.command(mod[loader.name] as never)
}
`
}

const outputPath = join(__dirname, "..", "src", "gyccode", "command-registry.ts")
writeFileSync(outputPath, generateRegistry(), "utf-8")
console.log(`Generated ${outputPath}`)