// Auto-generated command registry - DO NOT EDIT MANUALLY
// Generated by scripts/generate-command-registry.ts

import type { Argv } from "yargs"
import { Effect } from "effect"

type CommandLoader = { load: () => Promise<Record<string, unknown>>; name: string }

const ConsoleCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/account"), name: "ConsoleCommand" }
const AcpCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/acp"), name: "AcpCommand" }
const AgentCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/agent"), name: "AgentCommand" }
const AttachCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/attach"), name: "AttachCommand" }
const CliCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/cli"), name: "CliCommand" }
const DbCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/db"), name: "DbCommand" }
const ExportCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/export"), name: "ExportCommand" }
const GatewayCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/gateway"), name: "GatewayCommand" }
const GenerateCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/generate"), name: "GenerateCommand" }
const GithubCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/github"), name: "GithubCommand" }
const ImportCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/import"), name: "ImportCommand" }
const LearningCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/learning"), name: "LearningCommand" }
const McpCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/mcp"), name: "McpCommand" }
const MemoryCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/memory"), name: "MemoryCommand" }
const ModelsCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/models"), name: "ModelsCommand" }
const PairCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/pair"), name: "PairCommand" }
const PluginCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/plug"), name: "PluginCommand" }
const PrCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/pr"), name: "PrCommand" }
const ProvidersCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/providers"), name: "ProvidersCommand" }
const RunCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/run"), name: "RunCommand" }
const SendCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/send"), name: "SendCommand" }
const ServeCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/serve"), name: "ServeCommand" }
const SessionCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/session"), name: "SessionCommand" }
const StatsCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/stats"), name: "StatsCommand" }
const TuiThreadCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/tui"), name: "TuiThreadCommand" }
const UninstallCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/uninstall"), name: "UninstallCommand" }
const UpgradeCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/upgrade"), name: "UpgradeCommand" }
const WebCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/web"), name: "WebCommand" }
const WorkflowCommandLoader: CommandLoader = { load: () => import("@gyccode/cli/cmd/workflow"), name: "WorkflowCommand" }

export const COMMANDS: Record<string, CommandLoader> = {
  account: ConsoleCommandLoader,
  acp: AcpCommandLoader,
  agent: AgentCommandLoader,
  attach: AttachCommandLoader,
  cli: CliCommandLoader,
  db: DbCommandLoader,
  export: ExportCommandLoader,
  gateway: GatewayCommandLoader,
  generate: GenerateCommandLoader,
  github: GithubCommandLoader,
  import: ImportCommandLoader,
  learning: LearningCommandLoader,
  mcp: McpCommandLoader,
  memory: MemoryCommandLoader,
  models: ModelsCommandLoader,
  pair: PairCommandLoader,
  plug: PluginCommandLoader,
  pr: PrCommandLoader,
  providers: ProvidersCommandLoader,
  run: RunCommandLoader,
  send: SendCommandLoader,
  serve: ServeCommandLoader,
  session: SessionCommandLoader,
  stats: StatsCommandLoader,
  tui: TuiThreadCommandLoader,
  uninstall: UninstallCommandLoader,
  upgrade: UpgradeCommandLoader,
  web: WebCommandLoader,
  workflow: WorkflowCommandLoader,

  auth: ProvidersCommandLoader,
}

// Canonical command keys (excluding aliases) used to render the full --help list.
// Derived from COMMANDS by keeping the first key for each unique loader — aliases
// (e.g. `auth`→providers, `plug`→plugin) share a loader reference and are skipped.
// Single source of truth: the list cannot drift when commands or aliases change.
export const COMMAND_KEYS = (() => {
  const seen = new Set<CommandLoader>()
  const keys: string[] = []
  for (const [key, loader] of Object.entries(COMMANDS)) {
    if (seen.has(loader)) continue
    seen.add(loader)
    if (["tui","db"].includes(key)) continue
    if (key === "tui") continue
    keys.push(key)
  }
  return keys
})()

export const HIDDEN_COMMANDS_SET = new Set(["tui","db"])

export async function registerTui(cli: Argv, defaultEntry: boolean) {
  const mod = await import("@gyccode/cli/cmd/tui")
  const command = mod.TuiThreadCommand as unknown as Record<string, unknown>
  if (defaultEntry) cli.command({ ...command, command: "$0 [project]" } as never)
  else cli.command({ ...command, describe: false } as never)
}

export async function registerCommand(cli: Argv, loader: CommandLoader) {
  const mod = await loader.load()
  cli.command(mod[loader.name] as never)
}
